### ISSUE TITLE
Apply best practices for securing Tomcat

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/tomcat-runtime#16]
Here's one resource: https://www.owasp.org/index.php/Securing_tomcat

Resolution of this issue could be just creation of more focused issues after reviewing the various resources.

**Comment by cassand** [comment]
Here are some interesting additional resources:
* https://www.upguard.com/articles/15-ways-to-secure-apache-tomcat-8
* http://tomcat.apache.org/tomcat-8.0-doc/security-howto.html

**Comment by meltsufin** [comment]
These are great as well! Can you sift through all of these and create an issue for each? Plus, reference them here. Thanks!

**Comment by cassand** [comment]
All the general recommendations are applied, specific security improvement have they own issue.
So I will close this thread.
