### ISSUE TITLE
Remove tomcat manager

### ISSUE THREAD

**Issue by cassand** [GoogleCloudPlatform/tomcat-runtime#20]
Tomcat provide a manager application by default to help deploy new application without restarting the tomcat instance.

This application may be suppress as it would require to set default credentials to be used and may compromise the security of the tomcat instance.

**Comment by meltsufin** [comment]
Doesn't the use of `CATALINA_BASE` automatically remove the manager app?

**Comment by cassand** [comment]
Yes it does, the CATALINA_BASE/webapps directory is empty so the manager is disabled, but this is due to our implementation.

If at some point we decide to keep the manager we have the possibility to copy the original webapps directory into CATALINA_BASE.

**Comment by cassand** [comment]
As the manager have been removed in a previous commit (Transition from CATALINA_HOME to CATALINA_BASE) can I close this issue ?

**Comment by meltsufin** [comment]
yes
