### ISSUE TITLE
Make sure all tomcat server logs only go to stdout/stderr

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/tomcat-runtime#27]
This is to make sure that they are forwarded to Cloud Logging.

**Comment by cassand** [comment]
Most of the logging can be redirected to stdout/stderr but a few components such as [valves](https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html) do not use the main logging system and only offer the possibility send logs into a file

**Comment by meltsufin** [comment]
Are any of these valves on by default? Is there any way to make them write to stdout?

**Comment by cassand** [comment]
There is no valvle activated by default, there are manually specified in server.xml.

I don't see any trivial solution to redirect the output of the valve to stdout.
Here is the documentation https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html
