### ISSUE TITLE
Configure Default Tomcat Classpath Behavior (catalina.properties)

### ISSUE THREAD

**Issue by cassand** [GoogleCloudPlatform/tomcat-runtime#46]
Tomcat prevents the classpath from being modified by environment variables but offers an alternative way to configure the classpath through `catalina.properties`.

Official documentation: http://tomcat.apache.org/tomcat-8.5-doc/class-loader-howto.html
Here is an article related to this configuration: https://www.mulesoft.com/tcat/tomcat-classpath

Currently `catalina.properties` is not included in the runtime.

Continuation of #26.

**Comment by meltsufin** [comment]
@cassand I'm not sure I understand the purpose of this issue. What is the actual issue? Maybe clarify with an example?

**Comment by cassand** [comment]
We might want to restrict access to certain tomcat classes for example `org.apache.tomcat.*` or to library  used for implementation (e.g logging, session).

The Jetty runtime have similar restrictions by default.

**Comment by meltsufin** [comment]
So, is the issue that Tomcat server classes are accessible by the classloader of the webapp?

**Comment by cassand** [comment]
Yes exactly, do we want this behavior to be the default ?

We might also want to protect some libraries such as the gcp client library for logging

**Comment by meltsufin** [comment]
We should reproduce the default config of Tomcat to begin with. Then we can explore protecting other libraries.
