### ISSUE TITLE
Restructure readme doc for readability

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/tomcat-runtime#68]

**Comment by cassand** [comment]
I would suggest the following structure:

# Google Cloud Platform Tomcat Runtime Image

## Using the Tomcat image
### Running on App Engine Flexible 
#### Cloud SDK
#### Using custom Dockerfile
### Other platforms
## Configure the Runtime
### Tomcat properties
### Security best practices
## Modules
### Distributed sessions
### Stackdriver traces
## Development Guide
## Licensing

**Comment by meltsufin** [comment]
I would rename "Configure the Runtime" -> "Configuring the Runtime".
And make ("Module" -> "Optional Modules") a subsection of "Configuring the Runtime". Otherwise, it looks good to me.

**Comment by cassand** [comment]
I agree for "Configure the Runtime" we might even want to rename it "Configuring Tomcat" as users can add arbitrary properties to `catalina.properties`.

However, to me, it seems preferable to keep the "Optional Modules" part outside of the main configuration as those modules can be considered as an advanced usage.

I would imagine a typical user experience to be:
1 Deploy a sample application.
2 Configure Tomcat (e.g to match the configuration of their previous application).
3 Experiment with the modules (To leverage the integration with GCP).

Therefore merging the documentation about Tomcat configuration (that the user may know beforehand) and our modules configuration could be confusing.

What do you think?

**Comment by meltsufin** [comment]
Sounds reasonable. Let's continue the discussion in a PR.
